"""add_name_profiles_and_enrichment

Revision ID: 486edce77895
Revises: d51d69812631
Create Date: 2026-08-14 17:05:00.184710

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '486edce77895'
down_revision: Union[str, Sequence[str], None] = 'd51d69812631'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column('names', sa.Column('profile', sa.String(length=180), nullable=True))
    op.add_column('names', sa.Column('discoverability', sa.String(length=80), nullable=True))
    op.add_column('names', sa.Column('vibe', sa.String(length=100), nullable=True))
    op.add_column('names', sa.Column('nickname', sa.String(length=120), nullable=True))
    op.add_column('names', sa.Column('tags', sa.Text(), nullable=True))

    op.execute("UPDATE names SET profile = 'balanced' WHERE profile IS NULL")
    op.execute("UPDATE names SET discoverability = 'moderate' WHERE discoverability IS NULL")
    op.execute("UPDATE names SET vibe = 'classic' WHERE vibe IS NULL")
    op.execute("UPDATE names SET nickname = '' WHERE nickname IS NULL")
    op.execute("UPDATE names SET tags = '' WHERE tags IS NULL")

    op.alter_column('names', 'profile', nullable=False)
    op.alter_column('names', 'discoverability', nullable=False)
    op.alter_column('names', 'vibe', nullable=False)
    op.alter_column('names', 'nickname', nullable=False)
    op.alter_column('names', 'tags', nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('names', 'tags')
    op.drop_column('names', 'nickname')
    op.drop_column('names', 'vibe')
    op.drop_column('names', 'discoverability')
    op.drop_column('names', 'profile')
    # ### end Alembic commands ###
